# Generated by Django 3.0.5 on 2021-02-18 03:32

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=djongo.models.fields.JSONField(default=[]),
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
