# Generated by Django 3.0.5 on 2021-02-18 04:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20210218_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 18, 4, 35, 56, 283209, tzinfo=utc)),
        ),
    ]
